### PR TITLE
Fix VR usage: use camera projection matrix by current camera

### PR DESCRIPTION
**Pull request by kwnetzwelt**
This is a solution for the VR-issue described by users. It was tested using HTC Vive in Unity 2017. 

vr_issue
vr_issue_fixed

### CODE REVIEW

**Comment by kwnetzwelt** [comment]
Enabling shadows for spotlights works as well. 

shadow_fix_vr

**Review by SlightlyMad — CHANGES_REQUESTED** [review]
1. Drawing spot light mesh with GlobalCommandBuffer will not work correctly. GlobalCommandBuffer is executed before shadow map is rendered.
This could accidentally work if you have only one spotlight in your scene. Try to add second shadow casting spotlight and see what happens.

2. Using camera projection matrix with potentially large near clip plane can lead to some rendering artifacts. I'd rather keep the original code and use camera projection matrix only for VR. Can you detect VR with preprocessor or by code?

**Comment by kwnetzwelt** [comment]
The pull request now only adresses the matrix issue for vr. 

With regards to the spotlight issue. The CommandBuffers are simply not executed on the right eye. The reason: They are attached to shadowmap generation, which is only executed once (for the left eye) in a single camera setup. I have filed a bug report: https://fogbugz.unity3d.com/default.asp?968854_gmmukio2rnkjgibv

**Review by SlightlyMad — APPROVED** [review]

**Comment by OEN007** [comment]
@kwnetzwelt Great initiative! Which version of Unity have you been using to get this to work? *best* scenario on SteamVR so far after trying a bunch of Unity betas have been correct rendering on my left eye only. Is there something i need to do beyond the normal steps for this package?

**Comment by kwnetzwelt** [comment]
Unity also accepted the bug and will fix it sometime soon, so we can potentially do this with one camera in an upcoming unity release. I used Unity 2017.3.0b9 for this. As far as additional steps are concerned: For now you need to basically duplicate the camera and set each camera to render to one eye only.

**Comment by OEN007** [comment]
But as you said in the other thread, if you duplicate you will have two SteamVR_camera components. So do you remove SteamVR_camera from the duplicate camera?

**Pull request merged**
